#!/usr/bin/env python3
"""
Interactive setup for user-specific configuration

Creates config/user.yaml with your local paths
"""

import sys
from pathlib import Path
import yaml


def main():
    print("=" * 70)
    print("OpenFisca AI - User Configuration Setup")
    print("=" * 70)
    print()

    config_dir = Path(__file__).parent
    user_config_file = config_dir / "user.yaml"

    if user_config_file.exists():
        print(f"⚠️  {user_config_file} already exists!")
        response = input("Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("Cancelled.")
            sys.exit(0)
        print()

    # Ask for base path
    print("Where are your OpenFisca country packages located?")
    print("(e.g., /home/user/projets or /home/user/repositories)")
    print()

    base_path = input("Base path: ").strip()
    if not base_path:
        print("❌ Base path is required")
        sys.exit(1)

    base_path = Path(base_path).expanduser().absolute()

    if not base_path.exists():
        print(f"⚠️  {base_path} does not exist yet")
        create = input("Create it? (y/N): ").strip().lower()
        if create == 'y':
            base_path.mkdir(parents=True, exist_ok=True)
            print(f"✅ Created {base_path}")

    print()
    print("Optional: where do you store legislative source files?")
    print("(leave empty to skip legislative_sources.root in the generated config)")
    print()

    legislation_base_path = input("Legislative sources base path [skip]: ").strip()
    legislation_base_path = str(Path(legislation_base_path).expanduser().absolute()) if legislation_base_path else ""

    print()
    print("Which countries do you work with?")
    print("Enter country names separated by commas (e.g., tunisia, france)")
    print("Press Enter for default: tunisia")
    print()

    countries_input = input("Countries: ").strip()
    if not countries_input:
        countries = ['tunisia']
    else:
        countries = [c.strip() for c in countries_input.split(',')]

    print()
    print("Which country should be active by default?")
    active_country = input(f"Active country [{countries[0]}]: ").strip()
    if not active_country:
        active_country = countries[0]

    # Build config
    config = {
        'base_path': str(base_path),
        'active_country': active_country,
        'countries': {}
    }
    if legislation_base_path:
        config['legislation_base_path'] = legislation_base_path

    for country in countries:
        config['countries'][country] = {
            'existing_code': {
                'path': f"${{base_path}}/openfisca-{country}"
            }
        }
        if legislation_base_path:
            config['countries'][country]['legislative_sources'] = {
                'root': f"${{legislation_base_path}}/{country}"
            }

    # Write config
    print()
    print("=" * 70)
    print("Generated configuration:")
    print("=" * 70)
    print()
    print(yaml.dump(config, default_flow_style=False, allow_unicode=True))
    print()

    confirm = input("Save this configuration? (Y/n): ").strip().lower()
    if confirm == 'n':
        print("Cancelled.")
        sys.exit(0)

    with open(user_config_file, 'w', encoding='utf-8') as f:
        f.write("# User-specific local paths configuration\n")
        f.write("# Generated by config/setup.py\n")
        f.write("# Canonical override schema:\n")
        f.write("#   countries.<id>.existing_code.path\n")
        f.write("#   countries.<id>.legislative_sources.root\n\n")
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True)

    print(f"✅ Configuration saved to {user_config_file}")
    print()
    print("You can now use validation tools like:")
    print(f"  cd {base_path}/openfisca-{active_country}")
    print("  uv run python /path/to/openfisca-ai/tools/validate_units.py .")
    print("And from this repo:")
    print("  uv run python config/test_config.py")
    print()


if __name__ == "__main__":
    main()
